### PR TITLE
Explicitly define the branch to read logs from

### PR DESCRIPTION
**Pull request by Fydon**
This is an attempt to fix issue #3

### CODE REVIEW

**Comment by Fydon** [comment]
The two tests that I've added to test what I would expect to be returned by check are failing both with the current master and my branch. I would expect that check only returns revisions that are in the given branch, but [check is explicitly asking for descendants](https://github.com/concourse/hg-resource/blob/master/hgresource/check.go#L76) which may not be in the current branch. What is the reason for wanting descendants?

What is the reason for [updating to tip after a pull](https://github.com/concourse/hg-resource/blob/master/hg/hg.go#L86) instead of the latest revision on the branch?

At the moment my pipelines occasionally show failures, because they attempt to get revisions that aren't in the current branch and so immediately fail with the current version of hg-resource.

**Comment by vito** [comment]
@Fydon I'm not sure, to be honest - we don't use `hg` ourselves so don't really know enough. From your description it does sound broken. Do the latest commits fix that too?

**Comment by Fydon** [comment]
@vito Thank you so much for creating this resource. I would never have been able to use concourse without this. It is working most of the time, but occasionally reads the wrong revision.

I'm still trying to work out why it still isn't working as I would expect it to with the changes that I've made. I've been trying to write out to a file from inside the resource, but, even though the [write isn't returning an error](https://github.com/Fydon/hg-resource/blob/feature/DebugExplicityDefineBranch/hgresource/check.go#L39), the file doesn't exist.

Sorry I should have only opened the pull request after I'd work out how to test my changes.

**Comment by vito** [comment]
No worries. You could try `ioutil.WriteFile` instead? Or log to `stderr`? Also you're hijacking into the `check` container right? (`fly hijack -c pipeline-name/resource-name`)

**Comment by Fydon** [comment]
Thank you. I tried `ioutil.WriteFile` first and didn't have any success, but `stderr` works great. Doh! I thought that the `task` container was the right one to check, but the test was attempting to output the file if it existed.

**Comment by andreasf** [comment]
Hi there! Thanks for reporting the bug. I took a look at it and found 2-3 separate issues:

**Issue 1:** `GetLatestCommitId` and `GetDescendantsOf` should limit the revset to the current branch. The cleanest way to do this is to add a new set intersection with the branch (`... & branch('default')`) to the revset:

``` go
func (self *Repository) GetLatestCommitId() (output string, err error) {
    include := self.makeIncludeQueryFragment()
    exclude := self.makeExcludeQueryFragment()
    tagFilter := self.maybeTagFilter()
    revSet := fmt.Sprintf("last((((%s) - (%s)) & %s & branch('%s')) - desc('[ci skip]'))", include, exclude, tagFilter, self.getBranch())

    _, outBytes, err := self.run("log", []string{
        "--cwd", self.Path,
        "--rev", revSet,
        "--template", "{node}",
    })
    output = string(outBytes)
    if err != nil {
        err = fmt.Errorf("Error getting latest commit id: %s", err)
    }

    return
}

func (self *Repository) getBranch() string {
        if len(self.Branch) > 0 { 
            return self.Branch
        }
        return "default"
}
```

This makes both of your test cases pass. In fact, for `GetLatestCommitId` we only need a single test in which the latest commit of the repository is in another branch. Having a minimum number of test cases keeps our test suite clean and fast.

We haven't fixed `GetDescendantsOf` yet, though. Let's just take one of your tests and add a check that `check_uri_with_branch_from` can only see `$ref3` (and no other commits) after `$ref2` on master. This check is in the last 2 lines:

``` bash
test_check_ignores_commits_on_other_branches() {
  local repo=$(init_repo)
  local ref1=$(make_commit_to_branch $repo some-branch )
  local ref2=$(make_commit $repo)

  # Test initial check and clone
  local listWithRef1=$(echo "[{\"ref\": $(echo $ref1 | jq -R .)}]"|jq ".")
  assertEquals "$listWithRef1" "$(check_uri_with_branch $repo some-branch | jq '.')"

  # Checking a second time triggers pull instead of clone. Make sure that we still
  # get the same result.
  assertEquals "$listWithRef1" "$(check_uri_with_branch $repo some-branch | jq '.')"

  # Test that check with branch and previous commit id doesn't see commits of other branches
  local ref3=$(make_commit $repo)
  local emptyList="[]"
  assertEquals "$emptyList" "$(check_uri_with_branch_from $repo $ref1 some-branch | jq '.')"

  local ref4=$(make_commit_to_branch $repo some-branch )
  local listWithRef4=$(echo "[{\"ref\": $(echo $ref4 | jq -R .)}]"|jq ".")
  assertEquals "$listWithRef4" "$(check_uri_with_branch_from $repo $ref1 some-branch | jq '.')"

  local listWithRef3=$(echo "[{\"ref\": $(echo $ref3 | jq -R .)}]"|jq ".")
  assertEquals "$listWithRef3" "$(check_uri_with_branch_from $repo $ref2 default | jq '.')"
}
```

Now we make this test pass by adding another set intersection:

``` go
func (self *Repository) GetDescendantsOf(commitId string) ([]string, error) {
    include := self.makeIncludeQueryFragment()
    exclude := self.makeExcludeQueryFragment()
    tagFilter := self.maybeTagFilter()
    revSet := fmt.Sprintf("(descendants(%s) - %s) & %s & ((%s) - (%s)) & branch('%s') - desc('[ci skip]')",
        commitId, commitId, tagFilter, include, exclude, self.getBranch())

    _, outBytes, err := self.run("log", []string{
        "--cwd", self.Path,
        "--rev", revSet,
        "--template", "{node}\n",
    })

    output := string(outBytes)
    if err != nil {
        return []string{}, fmt.Errorf("Error getting descendant commits of %s: %s\n%s", commitId, err, output)
    }

    trimmed := strings.Trim(output, "\n\r ")
    if len(trimmed) == 0 {
        return []string{}, nil
    }

    commits := strings.Split(trimmed, "\n")
    return commits, nil
}
```

**Issue 2:** `hg.CloneOrPull` should always check out the right branch. This might not cause any issues in reality because `in` manually checks out the given revision, but it feels wrong. We don't currently have a failing test, so let's add one:

``` bash
test_check_checks_out_expected_branch_after_clone_and_pull() {
  local repo=$(init_repo)
  local ref1=$(make_commit_to_branch $repo some-branch )
  local ref2=$(make_commit $repo)

  # first check triggers clone
  local expected1=$(echo "[{\"ref\": $(echo $ref1 | jq -R .)}]"|jq ".")
  assertEquals "$expected1" "$(check_uri_with_branch $repo some-branch | jq '.')"
  assertEquals "some-branch" $(hg branch --cwd $TMPDIR/hg-resource-repo-cache)

  # second check triggers pull
  local expected2=$(echo "[{\"ref\": $(echo $ref1 | jq -R .)}]"|jq ".")
  assertEquals "$expected2" "$(check_uri_with_branch $repo some-branch | jq '.')"
  assertEquals "some-branch" $(hg branch --cwd $TMPDIR/hg-resource-repo-cache)
}
```

Having added this test, we can now make it pass by fixing `pull()`. You've already found out how, just checkout `--rev self.Branch` instead of `--rev tip`:

``` go
func (self *Repository) pull() (output []byte, err error) {
        _, output, err = self.run("pull", []string{
                "-q",
                "--cwd", self.Path,
        })
        if err != nil {
                err = fmt.Errorf("Error pulling changes from repository: %s", err)
                return
        }

        _, checkoutOutput, err := self.run("checkout", []string{
                "-q",
                "--cwd", self.Path,
                "--clean",
                "--rev", self.Branch,
        })
        output = append(output, checkoutOutput...)
        if err != nil {
                err = fmt.Errorf("Error updating working directory to tip: %s", err)
        }

        return
}
```

I'd like to encourage you to rewrite the history of your pull request branch a little:
- Each commit should best be motivated by a failing test
- Only change what's required to make the test pass. Refactoring is good, but don't make untested changes.
- Since it's 2-3 bugs, it should probably be 2-3 commits, not 10 ;-)

Thanks again!

**Comment by Fydon** [comment]
@andreasf Thank you for confirming that my changes are working.

The reason for my multiple commits is that getting both bash script and golang working together on Windows takes some effort, at least until some of the Insider Bash of Windows fixes are released, and therefore I was using a concourse pipeline to build and test my changes. I spent part of last weekend getting this working on Windows and so future changes I make will now be easier.

I'll try to clean up this pull request this week.

@vito I found that reason the test was failing was the result of the integration task using the latest docker image, rather than the output of the build. As a result of copying parts of the concourse pipeline for building this resource I now run the integration tests against a docker image that contains my changes.

**Comment by andreasf** [comment]
@Fydon a way to quickly iterate is to run the tests in Docker. For development, you can just add them to the Dockerfile like this:

```
FROM concourse/buildroot:hg

RUN mkdir -p /opt/resource
ADD hgresource/hgresource /opt/resource
ADD assets/askpass.sh /opt/resource
RUN chmod +x /opt/resource/*
RUN ln -s /opt/resource/hgresource /opt/resource/in; ln -s /opt/resource/hgresource /opt/resource/out; ln -s /opt/resource/hgresource /opt/resource/check

ADD test/ /opt/resource-tests/
RUN /opt/resource-tests/all.sh
```

With that, `scripts/test` will run Go tests, build a new container and then run the resource tests in Docker. You should be able to run it with Cygwin, or just rewrite it as a Windows batch script.

**Comment by Fydon** [comment]
@andreasf Thank you. I did steps similar to the Dockerfile manually in cygwin, as Go is producing Windows binaries. I've used your `test_check_checks_out_expected_branch_after_clone_and_pull` test, as I assume that you don't mind me committing it.

In my attempt to rewrite the history, the pull request closed, so I created a new one.

**Comment by Fydon** [comment]
@andreasf Could you please review #5?

**Pull request closed without merging**
