### PR TITLE
Enable 'evolve'

### PR DESCRIPTION
**Pull request by xavierzwirtz**
Rebased the evolve work done in #9. Added in a test. Changed to pulling mercurial from pip since evolve is hosted on pip. If that is an issue and we need to revert back to pulling the mercurial package, we will need to wait for alpine linux to release mercurial `5.0.2` due to [this bug in mercurial](https://bz.mercurial-scm.org/show_bug.cgi?id=6149).

I did not rebase the bookmark and topic features, these are not mercurial features I use, and I don't feel comfortable vetting the changes.

During testing I experienced some issues running tests, the race condition tests were very flakey. Unsure if that is due to the evolve introduction or something inherent to the tests.

Thank you @cdevienne for the initial work.

### CODE REVIEW

**Comment by cdevienne** [comment]
Thank you for giving it a second chance to get upstream.
I can do a new PR for bookmarks and topics once yours is merged.

**Comment by vito** [comment]
Thanks! Just did a quick merge conflict resolution, need to wait for the builds to run again now.

**Comment by xavierzwirtz** [comment]
`test_it_aborts_on_unknown_push_errors` is one of the tests I was seeing be flakey. Evolve slows down exchange somewhat, it might have made the race condition wait not long enough.

**Comment by vito** [comment]
Sorry for the delay, forgot to check back on the builds. Look like they passed. Thanks again!

**Comment by xavierzwirtz** [comment]
Lovely, thank you.

**Pull request merged**
